name: Bug Report
description: Submit a bug report for Reson
labels: ["bug"]
assignees:
  - cubxxw
  
type: bug

body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Clearly describe the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: Share the minimal steps to reproduce the issue.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (optional)
      description: OS, cloud provider, install method—if relevant.
    validations:
      required: false
