name: Bug Report
description: Submit a bug report for Reson
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: Provide detailed information about the bug. The more details you provide, the faster we can help.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the bug, aiming for minimal steps.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Include any other relevant information that could help with troubleshooting.

  - type: textarea
    id: cloudProvider
    attributes:
      label: Cloud provider
      description: Specify your cloud provider, if applicable.
    validations:
      required: true

  - type: textarea
    id: osVersion
    attributes:
      label: Operating System
      description: Provide your OS version. For Linux, use `cat /etc/os-release` and `uname -a`. For Windows, run `wmic os get Caption, Version, BuildNumber, OSArchitecture` and paste the output.
    validations:
      required: true

  - type: textarea
    id: installer
    attributes:
      label: Installation tools
      description: List any installation tools used, if applicable.
