name: "Database Issue Report"
description: "Template for reporting and analyzing database issues"
title: "Database Issue: [Short Description]"
labels: ["bug", "database"]
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: "问题概述"
      description: "简要描述问题的背景和影响。"
      placeholder: "描述问题..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 故障处理的整个过程"

  - type: textarea
    id: handling_process
    attributes:
      label: "故障处理过程"
      description: "详细记录故障发生后处理的步骤，包括但不限于故障检测、初步分析、临时修复和最终解决方案。"
      placeholder: "描述处理过程..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 故障原因分析"

  - type: textarea
    id: root_cause_analysis
    attributes:
      label: "故障原因分析"
      description: "深入分析导致故障的根本原因，包括技术因素、管理因素和其他潜在因素。"
      placeholder: "描述原因分析..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Ask 5 Whys"

  - type: textarea
    id: ask_5_whys
    attributes:
      label: "5 Whys 分析"
      description: "通过“5 Whys”方法深入挖掘问题根本原因。"
      placeholder: "1. 为什么会发生这个故障？\n2. 为什么会有这个技术因素/管理因素？\n3. 为什么没有在早期阶段发现？\n4. 为什么现有的检测机制未能捕捉？\n5. 为什么应急响应未能更快处理？"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 故障后续整改计划"

  - type: textarea
    id: remediation_plan
    attributes:
      label: "整改计划"
      description: "制定详细的整改计划，确保类似问题不会再次发生，包括技术改进、流程改进和团队改进。"
      placeholder: "描述整改计划..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 附件和参考资料"

  - type: textarea
    id: attachments
    attributes:
      label: "附件和参考资料"
      description: "添加相关日志、截图、监控数据等作为参考。"
      placeholder: "链接或附件描述..."

  - type: markdown
    attributes:
      value: "## 相关问题"

  - type: textarea
    id: related_issues
    attributes:
      label: "相关问题"
      description: "列出与此问题相关的其他 Issue 或讨论。"
      placeholder: "#相关Issue1\n#相关Issue2"
