name: Feature Request
description: Suggest an idea for this project
labels: ["feature"]
assignees:
  - cubxxw
type: feature

body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature you’d like to see.
      placeholder: |
        What should this feature do? Why is it useful?
    validations:
      required: false
